name: CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up PowerShell
        uses: actions/setup-powershell@v2
      - name: Run PowerShell Script
        run: pwsh ./your-script.ps1
